package org.argoprint.ui;

/*
 * ArgoPrintJDialog.java
 *
 * Created on den 17 november 2003, 14:38
 */

import org.argoprint.uml_interface.*;
import org.argoprint.engine.*;

import org.argouml.kernel.Project;
import org.argouml.kernel.ProjectManager;
import org.argouml.ui.ProjectBrowser;

import org.argouml.model.ModelFacade;

import java.awt.*;
import java.awt.event.*;
//import java.lang.reflect.*;
import java.lang.*;

import java.util.*;

import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.filechooser.*;
import java.awt.*;

/**
 *
 * @author  margy626
 */
public class ArgoPrintJDialog extends javax.swing.JDialog {

    private Logger log;
    
    /**
     * Sets the logger (log) to logger
     */
    public void setLog(Logger logger){ log = logger; }
    
    /** Creates new form JDialog */
    public ArgoPrintJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Template file:");
	//        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jLabel1);

        jTextField1.setText("myTemplate.xml");
	//        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, -1));
        getContentPane().add(jTextField1);

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

	//        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, 20));
        getContentPane().add(jButton3);



        jLabel2.setText("Output file:");
	//        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(jLabel2);

        jTextField2.setText("myOutput.xml");
	//        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));
        getContentPane().add(jTextField2);

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

	//        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 20));
        getContentPane().add(jButton4);



        jLabel3.setText("Data storage directory:");
	//        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(jLabel3);

        jTextField3.setText("myDataDirectory");
	//        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, -1));
        getContentPane().add(jTextField3);

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

	//        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 20));
        getContentPane().add(jButton5);

        jLabel4.setIcon(new javax.swing.ImageIcon("shrew.gif"));
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
	//        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 60));
        getContentPane().add(jLabel4);



        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

	//        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 30));
        getContentPane().add(jButton2);


        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

	//        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, 30));
        getContentPane().add(jButton1);

	//        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
	getContentPane().setLayout( new FlowLayout() );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ArgoPrint");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        
        setVisible( false );
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Add your handling code here:

        JFileChooser chooser = new JFileChooser();
        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the Java 2 SDK, Standard Edition.
        
        chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        int returnVal = chooser.showOpenDialog( this );
        if(returnVal == JFileChooser.APPROVE_OPTION) {
                jTextField3.setText( chooser.getSelectedFile().getPath() );
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the Java 2 SDK, Standard Edition.
        
        int returnVal = chooser.showOpenDialog( this );
        if(returnVal == JFileChooser.APPROVE_OPTION) {
                jTextField2.setText( chooser.getSelectedFile().getPath() );
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:  

        /******************************************************
         * This is where Engine is invoked!!!!!
         *
         * (Not in the comment ofcourse!)
         ******************************************************/
        
	UMLInterface umlIf = new UMLInterface();
	Environment env = new Environment();

	//setting argopprint for current project
	ProjectBrowser pb = ProjectBrowser.getInstance();
	Project p =  ProjectManager.getManager().getCurrentProject();
	
	umlIf.setLog(log);
	umlIf.setProject(p);
	umlIf.setProjectBrowser(pb);
	umlIf.setOutputPath( jTextField3.getText() );
	
	
	//Iterator for testing of Environment
	Iterator iter;

	//testing "simulated" template
	Object args[] = new Object[1];
	args[0] = p.getModel();
	
	Object response = umlIf.caller(new String("getOwnedElements"), args);
	
	if(response instanceof Collection){
	    //Iterator elementIterator = ((Collection) response).iterator();
	    iter = ((Collection) response).iterator();
	    env.addIterator(new String("element"), iter);
	    
	    //while(elementIterator.hasNext()){
	    while(iter.hasNext()){
	    
		//Object element = elementIterator.next();
		Object element = iter.next();
		args[0] = element;
		Object response2 = 
		    umlIf.caller(new String("isAClass"), args);
		
		if((response2 instanceof Boolean) && 
		   (((Boolean)response2).booleanValue())){
		    
		    log.info("Class name: " + 
			     ModelFacade.getFacade().getName(element));
		    
		    Object response3 = 
			umlIf.caller(new String("getOperations"), args);
		    
		    if(response3 instanceof Collection){
			iter = ((Collection) response3).iterator();
			//Iterator operationIterator = 
			//((Collection) response3).iterator(); 
			env.addIterator(new String("operation"), iter);
			while(iter.hasNext()){
			    //while(operationIterator.hasNext()){
			    //Object operation = operationIterator.next();
			    Object operation = iter.next();
			    log.info("operation name: " + 
				     ModelFacade.getFacade().getName(operation));
			}
			env.removeIterator(new String("operation"));
			iter = env.getIterator(new String("element"));
		    }
		}
	    }
	    env.removeIterator(new String("element"));
	}
        JOptionPane.showMessageDialog( this, "Output generation complete!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Add your handling code here:

        JFileChooser chooser = new JFileChooser();
        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the Java 2 SDK, Standard Edition.
        
        int returnVal = chooser.showOpenDialog( this );
        if(returnVal == JFileChooser.APPROVE_OPTION) {
                jTextField1.setText( chooser.getSelectedFile().getPath() );
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    

    //  /**
//       * @param args the command line arguments
//       */
//      public static void main(String args[]) {
//          new JDialog(new javax.swing.JFrame(), true).show();
//      }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
